### PR TITLE
Clarify the using maxRuns [Issue 8]

### LINKED ISSUE #8: How do you configure max runs?
It looks like there's support for a "max runs" (i.e. don't retry indefinitely), but I'm unclear how / where you'd configure that since the examples seem to suggest it's a drop in replacement for `test` -- https://github.com/mrloop/qunit-retry/blob/master/src/retry.js#L7

Thanks in advance and thanks for publishing this!

### PR DESCRIPTION
**Pull request by stephencweiss**
Closes #8 

Inspecting the tests, it seems that this was already demonstrated, however, I still think there's value in clarifying the defaults and covering it in the README.

- Made the default value of 1 explicit
- Clarified test case covering default
- Added context to README

### CODE REVIEW

**Comment by stephencweiss** [comment]
Also, the one thing I really didn't understand is the `testFn` in the constructor's signature. I also don't see any tests where a `testFn` is passed in, so I was unclear _how_ that worked.

**Comment by mrloop** [comment]
`testFn` is `QUnit.test` https://github.com/mrloop/qunit-retry/blob/a97063753d4e37f2ed4bc1e0de4a21eeaca2721b/main.js#L3, you use the `setup(QUnit.test)` which returns the `retry` function.

**Comment by stephencweiss** [comment]
Updated the change set to try to clarify how `maxRuns` relates to retry attempts.

**Comment by mrloop** [comment]
:tada: thanks @stephencweiss

**Pull request merged**
